theme: jekyll-theme-cayman
title: Backend Behavioral Security Series
description: Behavioral Sandboxing for Cloud-Native Backend Applications using Linux Seccomp-BPF and Landlock LSM (JVM Laboratory Example)
